# This file is part of the rockchip_stats package.

[tox]
envlist = py{3.7,3.8,3.9,3.10,3.11,3.12,3.13}
skip_missing_interpreters = true

[testenv]
setenv =
    TERM=linux
    TERMINFO=/etc/terminfo
    RTOP_TESTING=true
basepython =
    py3.7: python3.7
    py3.8: python3.8
    py3.9: python3.9
    py3.10: python3.10
    py3.11: python3.11
    py3.12: python3.12
    py3.13: python3.13
deps =
    check-manifest>=0.50
    flake8
    pytest
commands =
    check-manifest --ignore=tox.ini --ignore=rtop/tests* --ignore=docs* --ignore=examples*
    python setup.py check -m -s
    flake8 .
    py.test -v

[flake8]
max-line-length = 160
exclude = 
    .git,
    .tox,
    .venv*,
    *.egg,
    build,
    test.*,
    data
select = E,W,F

[pytest]
addopts = --ignore=rtop/tests_gui
log_cli_level = DEBUG
log_format = %(asctime)s [%(levelname)s] %(name)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
filterwarnings = ignore:.* is deprecated:DeprecationWarning
